const Constants = {
  RECEIVE_PROFILE: 'RECEIVE_PROFILE',
  RECEIVE_PROFILES: 'RECEIVE_PROFILES',
  REMOVE_PROFILE: 'REMOVE_PROFILE',
  RECEIVE_THIS_PROFILE: 'RECEIVE_THIS_PROFILE'
}

export default Constants;
